# Generated by Django 4.1.2 on 2022-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
