# Generated by Django 4.1.2 on 2022-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongoingfront', '0002_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
